### ISSUE TITLE
inquire-psbl-order 래퍼가 필요 합니다.

### ISSUE THREAD

**Issue by jasonleejusuk** [sharebook-kr/mojito#6]
염치없이 받아 쓰는 형편에... 
꼭 필요한 api같아서 요청 드립니다.

현재 한투api에서 미수 없이 주문할수 있는 금액을 보여주는 곳이 저 api 뿐이네요.
한투쪽에서도 inquire-psbl-order api를 이용하라고 하고...

현재 따로 불러오려고 하면서....
broker.access_token 으로 있는 토큰을 쓰면 될줄 알았는데...
집어넣으면 유효하지 않은 토큰이라고 나와서 당황중입니다. ㅠ_ㅠ

결국 모히토 래퍼와 기존 방식을 둘다 써야하는.......
(토큰이 꼬일것 같기도 하고.. 쩝..)

**Comment by brayden-jo** [comment]
0.1.4 버전에서 examples/koreainvestment/check_buy_order.py 예제로 확인하세요.

**Comment by jasonleejusuk** [comment]
감사합니다. ^^
